title: Josh's Github IO
description: My online thoughts and projects
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM

collections:
  people:
    output: true
    permalink: /dnd/people/:name/
  places:
    output: true
    permalink: /dnd/places/:name/
  sessions:
    output: true
    permalink: /dnd/sessions/:name/